#=================================
# Mapping trait abbrevs to full names
#=================================
name_map <-  c(
  ADHD = "ADHD",
  Age1stBth = "Age at First Birth",
  AgeMenar = "Age at Menarche",
  AgeMenop = "Age at Menopause",
  Agreeabl = "Agreeableness",
  ALevels = "A-Levels",
  AlzDis = "Alzheimer's",
  Anorexia = "Anorexia",
  AnxietyDx = "Anxiety Diagnosis",
  AutismSD = "Autism",
  Bipolar = "Bipolar",
  BirthWt = "Birth Weight",
  BMI_03 = "BMI (Elsworth)",
  BMI_16 = "BMI (Howe)",
  Cannabis = "Cannabis Use",
  CogFunc = "Cognitive Function",
  CollegeD = "College Degree",
  Confide = "Confides in Others",
  Conscien = "Conscientiousness",
  CRP = "C-Reactive Protein",
  EduYr = "Education (Years)",
  Extravert = "Extraversion",
  FaceHrAge = "Age of First Facial Hair",
  FatBody = "Body Fat Percentage",
  FI3_Word = "Word Interpol.",
  FI4PArith = "Positional Arithm.",
  FI5_FamRel = "Fluid Int. (Relations)",
  FI6CoArith = "Condit. Arithm.",
  FluIntSc = "Fluid Int. Score",
  GripStrR = "Grip Strength (Right)",
  Guilt = "Guilt",
  HbA1C_03 = "HbA1c",
  HipCirc = "Hip Circumference",
  Insomnia = "Insomnia",
  RheuArth = "Rheumatoid Arthritis",
  Irritable = "Irritability",
  Lonely = "Loneliness",
  MajDep = "Major Depression",
  ManicAll = "Mania (All)",
  MentDistr = "Mental Distress",
  Miserabl = "Miserableness",
  MoodSwg = "Mood Swings",
  NapDay = "Daytime Naps",
  Neurotic_30 = "Neuroticism",
  Obesity1 = "Obesity I",
  Obesity2 = "Obesity II",
  Openness = "Openness to Exper.",
  ProfQual = "Prof. Qual.",
  RiskTak = "Risk Taking",
  SchizoRip = "Schizophrenia (Ripke)",
  SchizoTru = "Schizophrenia (Trubetskoy)",
  SexPartn = "Sexual Partners",
  SleepDur = "Sleep Duration",
  SmokeCur_16 = "Smoking (Neale_1)",
  SmokeCur_25 = "Smoking (Neal_2)",
  Speeding = "Speeding",
  StandHgt = "Standing Height",
  Testost = "Testosterone",
  Triglyc_11 = "Triglycerides",
  Unenthus = "Unenthusiastic",
  UniverD = "University Degree",
  Urate = "Urate",
  WakeUp = "Wake-Up Time",
  WaistCir = "Waist Circumference",
  WHipRatio = "Waist-Hip Ratio",
  WorryEmb = "Worry/Embarrassment",
  YearsSch = "Years of Schooling",
  FEV1FVC = "FEV1/FVC Ratio",
  FastGlu = "Fasting Glucose",
  T2D = "Type 2 Diabetes",
  Top1pSur = "Top 1% Survival",
  Eczema = "Eczema",
  WalkPace = "Walking Pace",
  AlcCons = "Alcohol Consumption",
  MaxHR = "Maximum Heart Rate",
  BasoCt = "Basophil Count",
  IBD = "IBD",
  MonocyCt = "Monocyte Count",
  HeelDens = "Heel Bone Density",
  HighBP = "High Blood Pressure",
  LegArtSrg = "Leg Artery Surgery",
  ChronBr = "Chronic Bronchitis",
  FluIntAtt = "Fluid Intell. test",
  COPD = "COPD",
  ParkDis = "Parkinsons",
  PulmFib = "Death via Pulmonary Dis."
)

#=================================
# FIGURE 2
#=================================
fig2a_selected <- c(
  "ADHD", "AgeMenar", "ALevels", "AlzDis", "Anorexia", "AutismSD", "Bipolar", "BMI_03",
  "Cannabis", "EduYr", "FaceHrAge", "Guilt", "Insomnia", "Lonely", "MajDep", "NapDay",
  "Neurotic_30", "ProfQual", "RiskTak", "SchizoRip", "SchizoTru", "SexPartn", "SleepDur",
  "Speeding", "WakeUp", "Eczema", "AlcCons", "BasoCt", "IBD", "MonocyCt"
)

selected_traits_pca_fig2b <- c(
  "BMI_03", "CollegeD", "FM_Body", "GripStrR", "Insomnia", "Guilt", "MoodSwg",
  "MaxHR", "Obesity1","SmokeCur_16", "Testost","StandHgt", "FVitC_05", "SitHgt", "UniverD", "FluIntSc",
  "Wheeze", "WorryEmb","HipCirc","FFMTrunk","ImpedLeg","HlthRating","FP_Leg",
  "WakeUp","LongIll","FI3_Word","FP_Body","WalkPace","BirthWt","Neurotic_30",
  "BasMetR","FFM_Leg","HH_Inc","Neurotic_30","HighStrg","Anxious","ImpedArm","ApolipA1","FFM_Leg",
  "Weight","ImpedBody","NervFeel","Townsend","BMI_16","Body10Y","FatArm","PExpFl","VascHDxN","DiabetDx"
)

selected_traits_pca_fig2c <- c(
  "BMI_03", "EduYr","FM_Body", "GripStrR", "Insomnia", "Guilt", "MoodSwg", "RiskTak",
  "StandHgt", "FVitC_05", "SitHgt", "UniverD", "FluIntSc",
  "Wheeze", "WorryEmb","HipCirc","FFMTrunk","ImpedLeg","HlthRating","FP_Leg",
  "DiaBP_A59","WakeUp","LongIll","FI3_Word","FP_Body","WalkPace","BirthWt","Neurotic_30",
  "BasMetR","FFM_Leg","HH_Inc","Neurotic_30","HighStrg","Anxious","ImpedArm","FFM_Leg",
  "Weight","ImpedBody","NervFeel","Body10Y","FatArm","PExpFl","VascHDxN",
  "SysBP_A","SysBP_38","FamSatis"
)

#=================================
# FIGURE 3
#=================================
selected_traits_umap_fig3a <- c(
  "ADHD", "AgeMenar", "AlzDis", "ApolipB", "Bipolar", "BMI_03", "CanBlad", "CanProst", "CholesLDL", "Eczema", "EduYr",
  "FM_Body", "GripStrR", "Insomnia", "Guilt", "MoodSwg",
  "MaxHR", "Obesity1", "ParkDis", "RiskTak", "SchizoRip", "SchizoTru","SmokeCur_16",
  "Testost","StandHgt", "FVitC_05", "SitHgt", "UniverD", "FluIntSc",
  "Wheeze", "WHipRatio", "WorryEmb", "WtChg1Y","HipCirc","FFMTrunk","ImpedLeg","HlthRating","FP_Leg",
  "SysBP_38","DiaBP_A59","WakeUp","LongIll","Glaucoma","Eczema","Narcolep","ManicTalk","MentDistr","UTI",
  "URTI","T2D","CanLung","Cannabis","AsthmaDx96","RheuArth","CanOral","HeartAtt","CarpTunS","VitD",
  "AgeMenar","FaceHrAge","PulmFib","IBD","Agreeabl","AgeD_Mom","AgeD_Dad","NeutroCt"
)

selected_traits_umap_fig3be <- c(
  "A_AminTr", "AbdP_M", "AdenLung", "ADHD", "Age1stBth",
  "AgeD_Dad", "AgeD_Mom", "AgeMenar", "AgeMenop", "Agreeabl", "Albumin",
  "AlcCons", "AlcCur", "AlcPrev", "AlcWk", "ALevels", "AllergyDx",
  "AlzDis", "AmLatScl", "AnginaDx", "Anorexia", "AnxDep_GP", "AnxDep_Psy",
  "AnxietyDx", "Anxious", "AnxLongM", "ApolipA1", "ApolipB", "Appendic",
  "AsthmaDx96", "AsthmaDx97", "AutismSD", "BackP_M", "BasMetR", "BasoCt",
  "Bipolar", "BipolarDx", "BirthLen", "BirthWt", "BMI_03",
  "BMI_40", "BodyH2O", "BreastFd", "BrthFem", "BrthMale",
  "Calcium", "CanBlad", "CanCerv", "CanFSkin",
  "CanHemat", "CanHNeck", "CanLung", "Cannabis", "CanOral", "CanOroPh",
  "CanOvar", "CanPan", "CanProst", "CanSqCL", "CanTSkin", "CanUnBr",
  "CanUpBr", "CanUSkin", "CarpTunS", "Cataract", "Cellulit", "ChestP",
  "ChestPWlk", "ChObesity", "CholeCys", "CholesHDL", "CholesLDL", "Cholest_IR",
  "ChronBr", "ChronoTy", "CigsDay", "CMelSkin", "CNMSkin", "CoffCons",
  "CoffInt", "CogFunc", "ColdJob", "CollegeD", "Confide", "Conscien",
  "CookVeg", "COPD", "CornHys", "CornRes", "CRC",
  "Creat_Urn", "Creatin", "CRP_Lvl", "CRP", "CSEs", "D_AminTr",
  "Depress_S", "DepressDx", "DepressRx", "DepressSym", "DiabetDx", "DiabEye",
  "DiaBP_A59", "DiaBP_A92", "DiaBP", "DietVar", "DIY_Hvy", "DIY_Light",
  "DurScDis", "DVT_LegDx", "DVT_LungDx", "ECG_HR", "Eczema", "EduYr",
  "eGlFilR", "EmphCB", "EndoCard", "EosCt", "Extravert", "ExtremHt", "EyeProb", "FaceAge", "FaceHrAge", "Falls1Y",
  "FamSatis", "FastGlu", "FastIns", "FatBody", "FedUp",
  "Ferritin", "FEV1FVC", "FExpV1", "FFM_Leg",
  "FFMTrunk", "FI3_Word", "FI4PArith", "FI5_FamRel", "FI6CoArith",
  "FinanSat", "FluIntAtt", "FluIntSc", "FM_Leg", "FM_Trunk",
  "FP_Leg", "FP_Trunk", "Frac5Y", "FracFall", "FrndSat",
  "FruitInt", "FVitC_05", "GastRefl", "Glasses",
  "Glaucoma", "Glucose", "GlyHb", "Gout", "GripStrR", "Guilt",
  "HairP1", "HairP2", "HairP3", "HairP4", "Happiness", "Hayfever",
  "HbA1C_03", "HbA1C_41", "HbConc", "HctPct",
  "HearAid", "HearDiff", "HeartAtt", "HeelDens", "HH_Inc", "HighBP",
  "HighStrg", "HipCirc", "HOMABeta", "HOMAInsRe",
  "HotDrTmp", "HtChdAdu", "IBD", 
  "ImpedLeg", "InfHC", "InGrFac1", "Inhaler", "Insomnia",
  "Insul1Yr", "Iron", "Irrit2D", "Irritable", "JobSat", "LDLDir_IR",
  "LegArtSrg", "Leptin", "Leukemia", "Lonely", "Longsight",
  "LRTI_CC", "LRTI", "LymLeuk", "LymphCt_IR", "LymphCt", "LymphP_IR",
  "MaculDeg", "MajDep", "ManActiv", "ManCreat",
  "ManicAll", "ManicTalk", "ManLngth", "ManSleep", "MatchTm",
  "MaxHR", "MaxWorkL", "MCHbC_IR", "MenstrLn", "MentDistr", "MentHelp",
  "MicroAlb_00", "MicroAlb_97", "Miserabl", "ModActD", "MonocyCt", "MoodSwg",
  "MultScle", "NaK_U", "NapDay", "Narcolep", "NervFeel",
  "Neurotic_116", "Neurotic_30", "Neurotic_47", "NeutCt_IR", "NeutPct_IR", "NeutroCt",
  "NeuUppL", "NoBiPDep", "NoiseJob", "NoiseJobO", "NOxPlltn", "NumChild_27",
  "NumChild_60", "NVQHND", "ObCompD", "Obesity1", "Obesity2",
  "OccuPrCC", "OccuPrGR", "OophBilat", "Openness", "OsteoMyl",
  "OutdoorSum", "OverWt", "PainAll_M", "ParkDis", "PExpFl",
  "PFace_M", "PHead_M", "PHip3M", "Phosphat", "PhysAct",
  "PhysViol", "PKnee3M", "PlasCort",
  "PlsRate", "PlsRateA", "PlsW_P2P", "PlsWASI", "PlsWRI",
  "PNeck_M", "Pneu28D", "PneuCC", "PneuDth", "Pneumon", "ProfQual",
  "ProspMem", "PulmFib", "RBC_Ct_IR", "RBC_Dist_IR", "RheuArth", "RiskTak",
  "S_Angina", "S_HypTen", "Scer_IgA", "SchizoRip", "SchizoTru",
  "SelfAllg", "SelfAsth", "SelfT2D", "SensHurt", "Seps28D", "SepsCC",
  "Sepsis_69", "Sepsis_80", "SexPartn", "Shortsight", "SitHgt",
  "SleepAp", "SleepDis", "SleepDur", "SmokeCur_16", "SmokeCur_25", "SmokeEx_17",
  "SmokeEx_24", "SmokeEx_60", "SmokeEx6M", "SmokeInit", "SmokeLt",
  "SmokeNvr_06", "SmokeNvr_16", "SmokEver", "SnapBTm", "Snoring", "Speeding",
  "SphPwr_R", "SpiroRep", "StandHgt", "StrokeDx", "SuffNerv", "SunProt",
  "SysBP_18", "SysBP_38", "SysBP_A", "T2D", "TargHRAc", "TeaCons",
  "TeaInt", "TeloLen", "Testost", "TimeComp",
  "TotProt", "Townsend", "Transfrin", "Triglyc_11", "Triglyc_49", "UACR",
  "Unenthus", "UniverD", "Urate", "Urea", "UrineK", "UrineNa",
  "URTI", "UTI", "VascHDxN", "VigActiv", "VitD_Hyd25",
  "VitD", "VoiceAge", "WaistCir", "WakeUp", "WalkDur_16", "WalkDur_98",
  "WalkPace", "WaterInt", "WBC_Ct_IR", "WBC_Ct", "Weight", "Wellbein",
  "Wheeze", "WHipRatio", "WorryEmb", "YearsSch"
)

#=================================
# SUPP FIGURE 2
#=================================
supp2_selected <- c(
  "ADHD", "Age1stBth", "AgeMenar", "AgeMenop", "Agreeabl", "ALevels", 
                    "AlzDis", "Anorexia", "AnxietyDx", "AutismSD", "Bipolar", "BirthWt", 
                    "BMI_03", "BMI_16", "Cannabis", "CogFunc", "CollegeD", "Confide", 
                    "Conscien", "CRP", "EduYr", "Extravert", "FaceHrAge", "FatBody", 
                    "FI3_Word", "FI4PArith", "FI5_FamRel", "FI6CoArith", "FluIntSc", 
                    "GripStrR", "Guilt", "HbA1C_03", "HipCirc", "Insomnia", "RheuArth",
                    "Irritable", "Lonely", "MajDep", "ManicAll", "MentDistr", "Miserabl", 
                    "MoodSwg", "NapDay", "Neurotic_30", "Obesity1", "Obesity2", "Openness", 
                    "ProfQual", "RiskTak", "SchizoRip", "SchizoTru", "SexPartn", "SleepDur", 
                    "SmokeCur_16", "SmokeCur_25", "Speeding", "StandHgt", "Testost", 
                    "Triglyc_11", "Unenthus", "UniverD", "Urate", "WakeUp", "WaistCir", 
                    "WHipRatio", "WorryEmb", "YearsSch", "FEV1FVC", "FastGlu", "T2D", 
                    "Top1pSur", "Eczema", "WalkPace", "AlcCons", "MaxHR", "BasoCt", "IBD", 
                    "MonocyCt", "HeelDens", "HighBP")


umap_supp_fig_traits <- c(
  "ADHD", "AgeD_Dad", "AgeD_Mom", "AgeMenar", "AgeMenop", "Agreeabl",
  "AlcCons", "ALevels", "AlzDis", "AmLatScl", "AnginaDx", "Anorexia",
  "Anxious", "ApolipB", "Appendic", "AsthmaDx96", "AutismSD","BasMetR", "BasoCt",
  "Bipolar", "BirthWt", "BMI_03", "BreastFd", "BrthFem", "BrthMale",
  "Calcium", "CanBlad", "CanCerv", "CanLung", "Cannabis", "CanOral", "CanOvar", "CanProst",
  "CarpTunS", "Cataract", "ChestP", "CholesHDL",  "CoffCons",
  "CogFunc", "CollegeD", "Confide", "COPD", "CornHys", "CRP", "DiabetDx", "DiaBP",
  "Eczema", "EduYr", "EyeProb", "FaceAge", "FaceHrAge", "Falls1Y",
  "FastGlu", "FastIns", "FatArm", "FatBody", "Ferritin", "FEV1FVC",
  "FluIntSc", "FM_Body", "FP_Body", "FP_Leg", "FP_Trunk", "GastRefl", "Glasses",
  "Glaucoma", "Glucose", "Gout", "GripStrR", "Guilt", "HairP3", "HairP4", "Happiness", "Hayfever",
  "HbA1C_41", "HbConc", "HctPct", "HealthSat", "HearAid", "HeartAtt", "HeelDens", "HighBP",
  "HighStrg", "HipCirc", "IBD", "ImpedLeg", "Insomnia", "Iron", "Irritable",
  "Leptin", "Leukemia", "Lonely", "MaculDeg", "MajDep", "ManicAll", "ManicTalk", "MaxHR", "MentDistr",
  "Miserabl", "MonocyCt", "MornEve", "MultScle", "NaK_U", "NapDay", "Narcolep", "NervFeel",
  "Neurotic_116", "Neurotic_47", "NeutroCt", "Obesity1", "Obesity2", "Openness", "OsteoMyl",
  "OutdoorSum", "ParkDis", "PlsRate", "ProfQual", "PulmFib", "RBC_Ct_IR", "RheuArth", "RiskTak",
  "SchizoRip", "SchizoTru", "Sepsis_69", "SexPartn", "ShortBre", "Shortsight", "SitHgt",
  "SleepAp", "SleepDis", "SleepDur", "SmokeCur_16", "SmokeCur_25", "SmokEver", "Snoring", "Speeding",
  "StandHgt", "SuffNerv", "SunProt", "T2D", "TeaCons", "TeaInt", "TeloLen", "Testost", "Top1pSur",
  "Unenthus", "UniverD", "Urate", "Urea", "UrineNa", "URTI", "UTI", "VitD", "WakeUp", "WalkDur_98",
  "WalkPace", "Wheeze", "WHipRatio"
)

#=================================
# All traits
#=================================
all_traits <- c(
  "A_AminTr", "AbdP_3M", "AbdP_M", "AdenLung", "ADHD", "Age1stBth",
  "AgeD_Dad", "AgeD_Mom", "AgeMenar", "AgeMenop", "Agreeabl", "Albumin",
  "AlcCons", "AlcCur", "AlcPrev", "AlcWk", "ALevels", "AllergyDx",
  "AlzDis", "AmLatScl", "AnginaDx", "Anorexia", "AnxDep_GP", "AnxDep_Psy",
  "AnxietyDx", "Anxious", "AnxLongM", "ApolipA1", "ApolipB", "Appendic",
  "AsthmaDx96", "AsthmaDx97", "AutismSD", "BackP_M", "BasMetR", "BasoCt",
  "Bipolar", "BipolarDx", "BirthLen", "BirthWt", "BMI_03", "BMI_16",
  "BMI_40", "Body10Y", "BodyH2O", "BreastFd", "BrthFem", "BrthMale",
  "Bwt1stC", "Calcium", "CanBlad", "Canc_Dx", "CanCerv", "CanFSkin",
  "CanHemat", "CanHNeck", "CanLung", "Cannabis", "CanOral", "CanOroPh",
  "CanOvar", "CanPan", "CanProst", "CanSqCL", "CanTSkin", "CanUnBr",
  "CanUpBr", "CanUSkin", "CarpTunS", "Cataract", "Cellulit", "ChestP",
  "ChestPWlk", "ChObesity", "CholeCys", "CholesHDL", "CholesLDL", "Cholest_IR",
  "ChronBr", "ChronoTy", "CigsDay", "CMelSkin", "CNMSkin", "CoffCons",
  "CoffInt", "CogFunc", "ColdJob", "CollegeD", "Confide", "Conscien",
  "CookVeg", "COPD", "CornHys", "CornRes", "CoughMost", "CRC",
  "Creat_Urn", "Creatin", "CRP_Lvl", "CRP", "CSEs", "D_AminTr",
  "Depress_S", "DepressDx", "DepressRx", "DepressSym", "DiabetDx", "DiabEye",
  "DiaBP_A59", "DiaBP_A92", "DiaBP", "DietVar", "DIY_Hvy", "DIY_Light",
  "DurScDis", "DVT_LegDx", "DVT_LungDx", "ECG_HR", "Eczema", "EduYr",
  "eGlFilR", "EmphCB", "EndoCard", "EosCt", "Extravert", "ExtremHt",
  "EyeOthr", "EyeProb", "EyeTraum", "FaceAge", "FaceHrAge", "Falls1Y",
  "FamSatis", "FastGlu", "FastIns", "FatArm", "FatBody", "FedUp",
  "Ferritin", "FEV1FVC", "FEV1FVC7", "FExpV1", "FFM_Leg", "FFMBody",
  "FFMTrunk", "FI3_Word", "FI4PArith", "FI5_FamRel", "FI6CoArith", "FI8ChArith",
  "FinanSat", "FluIntAtt", "FluIntSc", "FM_Body", "FM_Leg", "FM_Trunk",
  "FP_Body", "FP_Leg", "FP_Trunk", "Frac5Y", "FracFall", "FrndSat",
  "FruitInt", "FVitC_05", "FVitC_36", "GastRefl", "GCSEs", "Glasses",
  "Glaucoma", "Glucose", "GlyHb", "Gout", "GripStrR", "Guilt",
  "HairP1", "HairP2", "HairP3", "HairP4", "Happiness", "Hayfever",
  "HbA1C_03", "HbA1C_41", "HbConc", "HctPct", "HeadP3M", "HealthSat",
  "HearAid", "HearDiff", "HeartAtt", "HeelDens", "HH_Inc", "HighBP",
  "HighStrg", "HipCirc", "HlthRating", "HOMABeta", "HOMAInsRe", "HospStay",
  "HotDrTmp", "HtAdoAdu", "HtChdAdu", "IBD", "ImmRetFr", "ImpedArm",
  "ImpedBody", "ImpedLeg", "InfHC", "InGrFac1", "Inhaler", "Insomnia",
  "Insul1Yr", "Iron", "Irrit2D", "Irritable", "JobSat", "LDLDir_IR",
  "LegArtSrg", "Leptin", "Leukemia", "Lonely", "LongIll", "Longsight",
  "LRTI_CC", "LRTI", "LymLeuk", "LymphCt_IR", "LymphCt", "LymphP_IR",
  "MaculDeg", "MajDep", "MajOp_26", "MajOp_37", "ManActiv", "ManCreat",
  "Manic2Day", "ManicAll", "ManicTalk", "ManLngth", "ManSleep", "MatchTm",
  "MaxHR", "MaxWorkL", "MCHbC_IR", "MenstrLn", "MentDistr", "MentHelp",
  "MicroAlb_00", "MicroAlb_97", "Miserabl", "ModActD", "MonocyCt", "MoodSwg",
  "MornEve", "MultScle", "NaK_U", "NapDay", "Narcolep", "NervFeel",
  "Neurotic_116", "Neurotic_30", "Neurotic_47", "NeutCt_IR", "NeutPct_IR", "NeutroCt",
  "NeuUppL", "NoBiPDep", "NoiseJob", "NoiseJobO", "NOxPlltn", "NumChild_27",
  "NumChild_60", "NVQHND", "ObCompD", "Obesity1", "Obesity2", "Obesity3",
  "OccuPrCC", "OccuPrGR", "OophBilat", "Openness", "OsteoMyl", "OthMedDx",
  "OutdoorSum", "OverWt", "PainAll_M", "ParkDis", "PBack3M", "PExpFl",
  "PFace_M", "PHead_M", "PHip_M", "PHip3M", "Phosphat", "PhysAct",
  "PhysViol", "PKnee_M", "PKnee3M", "PlasCort", "PLeg_St", "PLegWalk",
  "PlsRate", "PlsRateA", "PlsW_P2P", "PlsWASI", "PlsWRI", "PMsTrunk",
  "PNeck_M", "Pneu28D", "PneuCC", "PneuDth", "Pneumon", "ProfQual",
  "ProspMem", "PulmFib", "RBC_Ct_IR", "RBC_Dist_IR", "RheuArth", "RiskTak",
  "S_Angina", "S_HypTen", "S_OstArth", "Scer_IgA", "SchizoRip", "SchizoTru",
  "SelfAllg", "SelfAsth", "SelfT2D", "SensHurt", "Seps28D", "SepsCC",
  "Sepsis_69", "Sepsis_80", "SexPartn", "ShortBre", "Shortsight", "SitHgt",
  "SleepAp", "SleepDis", "SleepDur", "SmokeCur_16", "SmokeCur_25", "SmokeEx_17",
  "SmokeEx_24", "SmokeEx_60", "SmokeEx6M", "SmokeExpo", "SmokeInit", "SmokeLt",
  "SmokeNvr_06", "SmokeNvr_16", "SmokEver", "SnapBTm", "Snoring", "Speeding",
  "SphPwr_R", "SpiroRep", "StandHgt", "StrokeDx", "SuffNerv", "SunProt",
  "SysBP_18", "SysBP_38", "SysBP_A", "T2D", "TargHRAc", "TeaCons",
  "TeaInt", "TeloLen", "Testost", "TimeComp", "TinnitNo", "Top1pSur",
  "TotProt", "Townsend", "Transfrin", "Triglyc_11", "Triglyc_49", "UACR",
  "Unenthus", "UniverD", "Urate", "Urea", "UrineK", "UrineNa",
  "URTI", "UsedHRT", "UTI", "VascHDxN", "VigActiv", "VitD_Hyd25",
  "VitD", "VoiceAge", "WaistCir", "WakeUp", "WalkDur_16", "WalkDur_98",
  "WalkPace", "WaterInt", "WBC_Ct_IR", "WBC_Ct", "Weight", "Wellbein",
  "Wheeze", "WHipRatio", "WorryEmb", "WtChg1Y", "YearsSch"
)



umap_cluster_labels <- c("ADHD", "AgeD_Mom", "AlzDis", "Anorexia", "AnxLongM", "AnxietyDx", "ApolipB",
                         "BackP", "Bipolar", "BMI_16", "BreastFd", "CanBlad", "CanCerv", "CanLung", 
                         "CanOvar", "CanProst", "CarpTunS", "CoffCons", "CogFunc", "CornHys", "CRP", "DepressDx", "DiaBP", 
                         "DiabetDx", "Eczema", "ECG_HR", "EosCt", "Ferritin", "FruitInt","GastRefl", "Glasses", 
                         "FrndSat", "Glaucoma", "Gout", "GripStrR", "Happiness", "HearDiff", "HeartAtt", "HighBP", "ImpedLeg", 
                         "Iron", "Leukemia", "Lonely", "LymphCt", "Neurotic", "NeutroCt", "Openness", 
                         "OstArth", "OutdoorSum", "ParkDis", "PhysViol", "PlsRate", "ProspMem", "RheuArth", 
                         "RiskTak", "SchizoTru", "Sepsis_80", "SexPartn", "Shortsight", "SleepAp", 
                         "SleepDur", "SmokeCur", "Snoring", "StandHgt", "SunProt", "T2D", "TeloLen", 
                         "Triglyc_11","UniverD", "UTI", "VigActiv", "VitD", "WaistCir", "Wheeze")
